import { Component, Input } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  phosphorSquaresFour,
  phosphorCalendarBlank,
  phosphorClipboardText,
  phosphorFileText,
  phosphorWallet,
  phosphorUploadSimple,
  phosphorSignOut,
  phosphorWrench,
  phosphorTreeStructure,
  phosphorPlus,
  phosphorChartBar,
  phosphorProhibit,
  phosphorCheckCircle,
  phosphorX,
  phosphorCloudArrowUp,
  phosphorTrash,
  phosphorDownloadSimple,
  phosphorEnvelope,
  phosphorCaretDown,
  phosphorFunnel,
  phosphorListBullets,
  phosphorPackage,
  phosphorStack,
  phosphorLockKey,
  phosphorDotsThree,
  phosphorUser,
  phosphorCamera,
  phosphorWarningCircle,
  phosphorFloppyDisk,
  phosphorMagnifyingGlass,
  phosphorArrowsDownUp,
  phosphorStar,
  phosphorHeadset,
  phosphorTable,
  phosphorCheckSquare,
  phosphorRows,
  phosphorColumns,
  phosphorKanban,
  phosphorListDashes,
  phosphorEye,
  phosphorWarning,
  phosphorXCircle,
  phosphorCalendarCheck,
  phosphorPencilSimple,
  phosphorNotePencil,
  phosphorPencil,
  phosphorCircle,
  phosphorQuestion,
  phosphorArrowUp,
  phosphorArrowDown,
  phosphorInfo,
  phosphorGear,
  phosphorHammer,
  phosphorSignIn,
  phosphorMapPin,
  phosphorUsers,
  phosphorReceipt,
  phosphorSealCheck,
  phosphorHardHat,
  phosphorFlag,
  phosphorClock,
  phosphorMinusCircle,
  phosphorFolder,
  phosphorRadioButton,
  phosphorQrCode,
  phosphorPrinter,
  phosphorLink,
  phosphorCopy,
  phosphorEyeSlash,
  phosphorBuildings,
  phosphorBell,
  phosphorUserGear,
  phosphorPause,
  phosphorPlay
} from '@ng-icons/phosphor-icons/regular';

const ICON_MAP: Record<string, string> = {
  // Rail / navegação
  dashboard: 'phosphorSquaresFour',
  calendar_today: 'phosphorCalendarBlank',
  assignment: 'phosphorClipboardText',
  description: 'phosphorFileText',
  account_balance_wallet: 'phosphorWallet',
  upload_file: 'phosphorUploadSimple',
  logout: 'phosphorSignOut',
  business: 'phosphorBuildings',

  // Geral
  handyman: 'phosphorWrench',
  account_tree: 'phosphorTreeStructure',
  add: 'phosphorPlus',
  add_circle: 'phosphorPlus',
  bar_chart: 'phosphorChartBar',
  block: 'phosphorProhibit',
  calendar_month: 'phosphorCalendarBlank',
  calendar_check: 'phosphorCalendarCheck',
  check_circle: 'phosphorCheckCircle',
  close: 'phosphorX',
  cloud_upload: 'phosphorCloudArrowUp',
  delete: 'phosphorTrash',
  delete_outline: 'phosphorTrash',
  download: 'phosphorDownloadSimple',
  email: 'phosphorEnvelope',
  expand_more: 'phosphorCaretDown',
  filter_list: 'phosphorFunnel',
  format_list_bulleted: 'phosphorListBullets',
  inventory_2: 'phosphorPackage',
  layers: 'phosphorStack',
  list: 'phosphorListDashes',
  lock: 'phosphorLockKey',
  more_horiz: 'phosphorDotsThree',
  more_vert: 'phosphorDotsThree',
  person: 'phosphorUser',
  photo_camera: 'phosphorCamera',
  report_problem: 'phosphorWarningCircle',
  save: 'phosphorFloppyDisk',
  search: 'phosphorMagnifyingGlass',
  sort: 'phosphorArrowsDownUp',
  star_outline: 'phosphorStar',
  support_agent: 'phosphorHeadset',
  table_chart: 'phosphorTable',
  task_alt: 'phosphorCheckSquare',
  view_agenda: 'phosphorRows',
  view_column: 'phosphorColumns',
  view_kanban: 'phosphorKanban',
  view_list: 'phosphorListDashes',
  visibility: 'phosphorEye',
  visibility_off: 'phosphorEyeSlash',
  warning: 'phosphorWarning',
  error: 'phosphorXCircle',
  edit: 'phosphorPencilSimple',
  create: 'phosphorNotePencil',
  radio_button_unchecked: 'phosphorCircle',
  engineering: 'phosphorWrench',
  help: 'phosphorQuestion',
  cancel: 'phosphorXCircle',
  arrow_upward: 'phosphorArrowUp',
  arrow_downward: 'phosphorArrowDown',
  info: 'phosphorInfo',
  settings: 'phosphorGear',
  build: 'phosphorHammer',
  login: 'phosphorSignIn',
  location_on: 'phosphorMapPin',
  group: 'phosphorUsers',
  request_quote: 'phosphorReceipt',
  verified: 'phosphorSealCheck',
  construction: 'phosphorHardHat',
  fact_check: 'phosphorClipboardText',
  flag: 'phosphorFlag',
  clock: 'phosphorClock',
  minus_circle: 'phosphorMinusCircle',
  folder: 'phosphorFolder',
  radio_button_checked: 'phosphorRadioButton',
  qr_code: 'phosphorQrCode',
  pause: 'phosphorPause',
  play_arrow: 'phosphorPlay',
  print: 'phosphorPrinter',
  link: 'phosphorLink',
  copy: 'phosphorCopy',
  remove_circle_outline: 'phosphorMinusCircle',
  pending_actions: 'phosphorWarningCircle',
  admin_panel_settings: 'phosphorGear',
  notifications: 'phosphorBell',
  assign_technician: 'phosphorUserGear'
};

const ICONS = {
  phosphorSquaresFour,
  phosphorCalendarBlank,
  phosphorClipboardText,
  phosphorFileText,
  phosphorWallet,
  phosphorUploadSimple,
  phosphorSignOut,
  phosphorWrench,
  phosphorTreeStructure,
  phosphorPlus,
  phosphorChartBar,
  phosphorProhibit,
  phosphorCheckCircle,
  phosphorX,
  phosphorCloudArrowUp,
  phosphorTrash,
  phosphorDownloadSimple,
  phosphorEnvelope,
  phosphorCaretDown,
  phosphorFunnel,
  phosphorListBullets,
  phosphorPackage,
  phosphorStack,
  phosphorLockKey,
  phosphorDotsThree,
  phosphorUser,
  phosphorCamera,
  phosphorWarningCircle,
  phosphorFloppyDisk,
  phosphorMagnifyingGlass,
  phosphorArrowsDownUp,
  phosphorStar,
  phosphorHeadset,
  phosphorTable,
  phosphorCheckSquare,
  phosphorRows,
  phosphorColumns,
  phosphorKanban,
  phosphorListDashes,
  phosphorEye,
  phosphorWarning,
  phosphorXCircle,
  phosphorCalendarCheck,
  phosphorPencilSimple,
  phosphorNotePencil,
  phosphorPencil,
  phosphorCircle,
  phosphorQuestion,
  phosphorArrowUp,
  phosphorArrowDown,
  phosphorInfo,
  phosphorGear,
  phosphorHammer,
  phosphorSignIn,
  phosphorMapPin,
  phosphorUsers,
  phosphorReceipt,
  phosphorSealCheck,
  phosphorHardHat,
  phosphorFlag,
  phosphorClock,
  phosphorMinusCircle,
  phosphorFolder,
  phosphorRadioButton,
  phosphorQrCode,
  phosphorPrinter,
  phosphorLink,
  phosphorCopy,
  phosphorEyeSlash,
  phosphorBuildings,
  phosphorBell,
  phosphorUserGear,
  phosphorPause,
  phosphorPlay
};

@Component({
  selector: 'app-icon',
  standalone: true,
  imports: [NgIcon],
  providers: [provideIcons(ICONS)],
  template: `<ng-icon [name]="resolvedName" [size]="size"></ng-icon>`,
  styles: [`:host { display: inline-flex; line-height: 1; }`]
})
export class IconComponent {
  @Input() name = '';
  @Input() size = '1em';

  get resolvedName(): string {
    return ICON_MAP[this.name] ?? this.name;
  }
}
